services:
  nextjs:
    build: ./
    container_name: nextjs
    hostname: nextjs
    ports:
      - 3000:3000
    networks:
      - app_network
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cache:/var/cache/nginx
    depends_on:
      - nextjs
    networks:
      - app_network
networks:
  app_network:
    external: true
