services:
  nextjs:
    build: ./
    container_name: nextjs
    hostname: nextjs
    ports:
      - 80:80
    networks:
      - app_network
    environment:
      - NEXTAUTH_URL=http://nextjs:3000/
      - NEXTAUTH_SECRET=uu/k0H94LFkIGQozSLSG3lsWPrJUeLipWX1VvDDkgqw=
      - NEXT_PUBLIC_API_URL=http://gateway:8080
  nginx:
    image: nginx:alpine
    ports:
      - 8090:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cache:/var/cache/nginx
    depends_on:
      - nextjs
    networks:
      - app_network
networks:
  app_network:
    external: true
