version: "3.8"
services:
  nextjs:
    build: ./
    ports:
      - 80:80
    networks:
      - web
  nginx:
    image: nginx:alpine
    ports:
      - 8090:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cache:/var/cache/nginx
    depends_on:
      - nextjs
    networks:
      - web
networks:
  web:
    driver: bridge
